apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devshack-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: princewillopah/devshack-frontend:serve-1.1.6
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "104.248.193.10:5000"
            - name: REACT_APP_BACKEND_URL
              value: "104.248.193.10:5000"           