apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devshack-ns
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000  # service port
      targetPort: 3000  # container port
  type: LoadBalancer