apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devshack-ns
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9wcmluY2V3aWxsb3BhaGRldjpDQmc1WEhnUDZEdTVjNExzQGNsdXN0ZXItMS56M2pqYWoyLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyLTE=
